Added class Storage.php
codex-team/capella pull request #10
Opened 2017-10-12 18:24 UTC by AndreySuworow

2017-10-12 18:33 UTC, talyguryn requested changes

2017-10-12 18:33 UTC, talyguryn commented on Storage.php
> +    const AWS_KEY = ""; //Amazon s3 cloud authorisation key
это лучше писать не тут, а создать рядом конфиг, который будет подгружаться в конструкторе этого класса, и семпл этого конфига

2017-10-12 18:35 UTC, talyguryn requested changes

2017-10-12 18:35 UTC, talyguryn commented on Storage.php
> +    public function putObject($tmpFileName)
`putObject` -> `uploadFile`

2017-10-12 18:38 UTC, talyguryn requested changes

2017-10-12 18:38 UTC, talyguryn commented on Storage.php
> +     * @return array
array чего? какие поля на выходе получаем?

2017-10-15 12:13 UTC, talyguryn approved these changes

2017-10-15 12:16 UTC, neSpecc approved these changes

2017-10-15 12:16 UTC, gohabereg approved these changes

2017-10-15 12:18 UTC, merged