Add image processing class
codex-team/capella pull request #11
Opened 2017-10-13 17:17 UTC by vovaksenov99

2017-10-13 17:31 UTC, gohabereg requested changes

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +     * @param $extension extension which we want to valid
`we want to validate`
и можно без `which`

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +     * @param $extension extension which we want to valid
Еще желательно указывать тип параметра
`@param {String} $extension — extensi...`

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +        for($i=0;$i<count($this->validExtensions);$i++)
Есть стандартный метод для поиска по массиву

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +    function isValidExtension($extension)
Функцию можно сделать приватной

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +        $this->imagick = null;
Не уверен, что это надо самому чистить. Можешь почитать про сбор мусора в php

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +    function cropImage($x,$y,$cropWidth,$cropHeight)
Пробелы после запятых

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +        header('Content-Type: image');
Сюда можно конкатенировать тип изображения: `image/jpeg`, `image/png` etc

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +    function generateRandomName($length = 10) {
Функция нигде не используется, можно выпилить

2017-10-13 17:31 UTC, gohabereg commented on ImageProcessing.php
> +    public $validExtensions = array('png','gif','jpeg');
Это точно должно быть `public`?

2017-10-13 18:21 UTC, gohabereg requested changes

2017-10-13 18:21 UTC, gohabereg commented on ImageProcessing.php
> +        foreach ($this->validExtensions as $value){
Глянь `in_array`

2017-10-13 18:21 UTC, gohabereg commented on ImageProcessing.php
> +     * @param {int} $x start crop position
Я думаю там должно быть `Integer`. Но лучше проверить в документации к phpdoc

2017-10-13 18:29 UTC, vovaksenov99 commented on ImageProcessing.php
> +     * @param {int} $x start crop position
Я вижу что можно и так и так. 
https://docs.phpdoc.org/references/phpdoc/types.html

2017-10-14 02:55 UTC, gohabereg approved these changes
Совсем идеально было бы переместить приватное свойство под публичные и приватный метод под публичные. И сами публичные методы обозначить ключевым словом `public`.

Свойство `imagick` лучше сделать приватным

2017-10-14 12:29 UTC, neSpecc requested changes

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +        if((@$this->imagick ->readImage($path)) == false){
лишний пробел перед стрелкой и лишние скобки

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +     * @param {String} $path path to image
какой именно путь? внешний или на локальный файл? нужно уточнить в комментах

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +     * @param {String} $extension we want to valid
validate

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +        if((@$this->imagick ->readImage($path)) == false){
и лучше не помещать в ифы вызовы функций, сделай это выше, чтобы было понятно, откуда в `$this->imagick ` берется файл

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +    function cropImage($x, $y, $cropWidth, $cropHeight)
должна быть возможность передать только одну сторону, и координаты должны определяться автоматически — если их нет, то ресайзить по меньшей стороне и вырезать из центра.

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +    function resizeImage($resizeWidth,$resizeHeight,$filter,$blur,$fit = false)
пробелы после запятых

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +     * @param {bool} $fit
нужно описать параметр.

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +     * @param {int} $filter Refer to the list of filter constants
filter и blur можно вообще убрать или сделать не обязательными. Разработчик не должен об этом думать, при выполнении команды resize

2017-10-14 12:29 UTC, neSpecc commented on ImageProcessing.php
> +        header('Content-Type: image/'.$this->imageExtension);
нужны пробелы вокруг точки

2017-10-14 14:14 UTC, gohabereg requested changes

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +	private $validExtensions = array('png', 'gif', 'jpeg');
Что-то с отступом

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +		$readResult = @$this->imagick->readImage($path);
Отступ

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +        if($readResult == false){
`!$readResult`

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +            $this->resizeImage(null, $cropHeight);
Зачем при кропе ресайзить?

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +            $this->imagick->scaleImage($this->width * $k, $resizeHeight);
Если указать вместо одного из параметров `scaleImage()` 0, то он посчитается автоматически

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +    public $imageExtension;
Думаю, можно убрать `image` из имени переменной

2017-10-14 14:14 UTC, gohabereg commented on ImageProcessing.php
> +    public $imagePath = null;
И тут тоже убрать `image`

2017-10-14 14:21 UTC, vovaksenov99 commented on ImageProcessing.php
> +            $this->resizeImage(null, $cropHeight);
Чтобы вырезать центральную часть лучше всего. Идея  @neSpecc

2017-10-14 14:22 UTC, vovaksenov99 commented on ImageProcessing.php
> +            $this->imagick->scaleImage($this->width * $k, $resizeHeight);
Лучше считать самому и подавать гарантировано корректно

2017-10-14 14:31 UTC, vovaksenov99 commented on ImageProcessing.php
> +	private $validExtensions = array('png', 'gif', 'jpeg');
странно, у меня в документе норм...

2017-10-14 14:55 UTC, gohabereg approved these changes

2017-10-15 10:24 UTC, talyguryn requested changes

2017-10-15 10:24 UTC, talyguryn commented on ImageProcessing.php
> +    public function echoImage()
уж лучше не просто echo вывод изображения, а return. модуль ImageProcessing должен уметь получать на вход изображение, обрабатывать и возвращать, а не выводить. вопрос вывода изображения будет решать контроллер, который вызовет этот класс

2017-10-15 10:24 UTC, talyguryn commented on ImageProcessing.php
> +     *
приведи все комментарии в приличный вид, чтобы было приятно смотреть. в первой строчке краткое описание работы функции, каким бы ясным не было название.

2017-10-15 12:06 UTC, neSpecc requested changes

2017-10-15 12:06 UTC, neSpecc commented on ImageProcessing.php
> +            $this->resizeImage(null, $cropHeight);
не учитываются вертикальные изображния

2017-10-15 22:06 UTC, neSpecc approved these changes

2017-10-15 22:09 UTC, talyguryn commented
Притяни мастера и убери класс в папку lib

2017-10-15 22:09 UTC, talyguryn requested changes

2017-10-15 22:09 UTC, talyguryn commented on ImageProcessing.php
> +class ImageProcessing
Доки с примерами использования нужны

2017-10-15 23:37 UTC, talyguryn approved these changes

2017-10-15 23:37 UTC, merged

2017-10-16 13:15 UTC, talyguryn commented
closes #3