Add Docker server
codex-team/capella pull request #110
Opened 2017-12-08 17:21 UTC by talyguryn

2017-12-10 20:21 UTC, n0str requested changes

2017-12-10 20:21 UTC, n0str commented on docker/docker-compose.yml
> +            - ../capella:/var/www
docker-compose.yml следует вынести в корневую директорию проекта.

2017-12-10 20:21 UTC, n0str commented on docker/docker-compose.yml
> +        build: php5.6-fpm
Давай использовать php7.2-fpm или аналогичный образ

2018-03-04 07:41 UTC, khaydarov approved these changes

2018-03-04 07:43 UTC, PolinaShneider approved these changes

2018-03-04 07:46 UTC, merged