Add files via upload
codex-team/capella pull request #12
Opened 2017-10-13 20:21 UTC by dankunis

Пока оставил нерешенной одну проблему - не знаю, как получить размер файла по ссылке прежде чем загружать. (Однако нашел способ через функцию get_headers, но дело в том, что она работает только для http).

2017-10-13 20:23 UTC, vovaksenov99 commented on Uploader.php
> +const MaxFileSize = 5000000000000;
У тебя одна константа большими буквами, а другая нет

2017-10-13 20:24 UTC, n0str commented
It's enough to just make HTTP HEAD request, get Content-size header and disconnect.
https://stackoverflow.com/questions/2602612/php-remote-file-size-without-downloading-file

2017-10-13 20:36 UTC, talyguryn requested changes

2017-10-13 20:36 UTC, talyguryn commented on Uploader.php
> +const MaxFileSize = 5000000000000;
ставь пределом 15 МБ. должно хватить для большинства задач.

2017-10-13 20:36 UTC, talyguryn commented on Uploader.php
> +const EXPANSIONS = array('image/jpg', 'image/png', 'image/jpeg', 'image/gif', 'jpg', 'png', 'jpeg', 'gif');
EXTENSIONS ?

2017-10-13 20:36 UTC, talyguryn commented on Uploader.php
> +if(isset($_POST['FileSubm'])) {
почему ты проверяешь кнопку, а не поле с файлом?

2017-10-13 20:36 UTC, talyguryn commented on Uploader.php
> +    $FileName = $_FILES['image']['name'];
Каждого поля может не оказаться в массиве. Надо бы добавить проверки на существование

2017-10-14 15:02 UTC, gohabereg commented on Uploader.php
> +const MAXFILESIZE = 125829120; #15 МБ
Лучше расписать как произведение 15 * 1024 * 1024 * 8. Так будет легче потом поменять значение

2017-10-14 15:02 UTC, gohabereg commented on Uploader.php
> +const EXTENSIONS = array('image/jpg', 'image/png', 'image/jpeg', 'image/gif', 'jpg', 'png', 'jpeg', 'gif');
`image/<type>` это не расширение, это MIME-type

2017-10-15 21:20 UTC, gohabereg approved these changes

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +    public function Initialization()
Эта функция должна быть конструктором

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +    private $FileSize;
Переменные с маленькой буквы

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +const MAX_FILE_SIZE = 15*1024*1024*8; #15 МБ
Это можно в класс занести

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +    public function Checking()
Имена методов тоже с маленькой буквы

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +        if(!in_array($this->FileExp, EXTENSIONS)) {
Разнеси все-таки проверки на разные методы `checkSize`, `checkExtension`

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +            echo "Wrong file type.";
Лучше, наверное, кидать эксепшн

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +            echo $imgURI;
Лучше в методах класса не выводить ничего на страницу. Просто сделай `return $imageURL`

2017-10-15 21:20 UTC, gohabereg commented on ImageLink.class.php
> +<?php
По этому классу такие же комменты как и выше

2017-10-15 21:20 UTC, gohabereg commented on FileImage.class.php
> +    public function Checking()
Этот метод лучше сделать приватным

2017-10-15 21:20 UTC, gohabereg requested changes
missclick

2017-10-16 11:05 UTC, dankunis commented on FileImage.class.php
> +    public function Checking()
Если сделать приватным, то как вызывать его в Uploader.php?
И зачем это делать? (Опять же, я не спорю, а пытаюсь понять логику)

2017-10-16 11:09 UTC, dankunis commented on FileImage.class.php
> +    public function Checking()
Ты хочешь, чтобы метод загрузки внутри себя вызывал метод проверки?

2017-10-16 19:12 UTC, gohabereg requested changes

2017-10-16 19:12 UTC, gohabereg commented on FileImage.class.php
> +class wrongFileSize extends Exception {}
Мы обычно так не запариваемся, но если уж сделал класс, то назови с большой буквы

2017-10-16 19:12 UTC, gohabereg commented on FileImage.class.php
> +        try {
Эксепшены в классах обычно делаются для того, чтобы они упали снаружи. Так что try...catch тоже лучше делать снаружи, а не тут

2017-10-16 19:12 UTC, gohabereg commented on FileImage.class.php
> +        $imgURI = $storage->getImage($imgID);
Надо будет удалить файл

2017-10-16 19:12 UTC, gohabereg commented on FileImage.class.php
> +            $this->filePath = $_FILES['ImageFile']['tmp_name'];
Лучше сделать перемещение файла через `move_uploaded_file`, она проверяет, действительно ли файл был загружен на сервер через post запрос

2017-10-16 19:12 UTC, gohabereg commented on ImageLink.class.php
> +        if (!in_array($this->fileExp, FileImage::EXTENSIONS)) {
Тут ты обращаешься к другому классу, который логически никак не связан с этим. Лучше тогда подумать в сторону наследования обоих классов от одного, в котором будут методы проверки, разрешенные расширения, размер и т.д.

2017-10-16 19:12 UTC, gohabereg commented on ImageLink.class.php
> +        $this->fileName = basename($_GET['ImageLink']);
Лучше не брать ссылку из гет параметров, а передавать ее в конструктор как параметр

2017-10-16 20:14 UTC, talyguryn requested changes
притяни мастер в свою ветку

2017-10-16 20:14 UTC, talyguryn commented on FileImage.class.php
> +class wrongFileSize extends Exception {}
а оно того стоит?

2017-10-16 20:14 UTC, talyguryn commented on FileImage.class.php
> +    const EXTENSIONS = array('image/jpg', 'image/png', 'image/jpeg', 'image/gif', 'jpg', 'png', 'jpeg', 'gif');
чтобы уж совсем по красоте

```
const EXTENSIONS = array(
    'image/jpg', 'jpg',
    'image/png', 'png',
    'image/jpeg', 'jpeg',
    'image/gif', 'gif'
);

2017-10-16 20:14 UTC, talyguryn commented on FileImage.class.php
> +        require_once 'lib/AWS/Storage.php';
у тебя же нет сейчас этих файлов. притяни мастер в свою ветку

2017-10-16 20:14 UTC, talyguryn commented on ImageLink.class.php
> +require_once 'FileImage.class.php';
есть ли смысл в название добавлять class?

2017-10-16 20:14 UTC, talyguryn commented on ImageLink.class.php
> +
лишняя строка

2017-10-16 20:14 UTC, talyguryn commented on ImageLink.class.php
> +class LinkImage
комментарий с примером использования

2017-10-16 20:14 UTC, talyguryn commented on ImageLink.class.php
> +    private function checkExtension()
к каждой функции надо оставлять комментарии

2017-10-16 20:14 UTC, talyguryn commented on ImageLink.class.php
> +        file_put_contents($this->fileName, file_get_contents($_GET['ImageLink']));
разделяй смысловые части пустыми строками

2017-10-16 20:14 UTC, talyguryn commented on ImageLink.class.php
> +        require_once('lib/AWS/Storage.php');
может лучше подключать модули в начале файла?

2017-10-16 20:14 UTC, talyguryn commented on Uploader.php
> +}
`} elseif (...) {`

2017-10-16 20:14 UTC, talyguryn commented on Uploader.php
> +if(!empty($_GET['ImageLink']) and isset($_GET['LinkSubm'])) {
`if (...) {`

2017-10-16 20:14 UTC, talyguryn commented on Uploader.php
> +    <input type="submit" name="LinkSubm" value="Accept"/>
возьми name проще и понятнее

2017-10-16 20:14 UTC, talyguryn commented on Uploader.php
> +    <input type="submit" name="FileSubm" value="Accept"/>
возьми name проще и понятнее

2017-10-16 20:15 UTC, gohabereg commented on FileImage.class.php
> +    const EXTENSIONS = array('image/jpg', 'image/png', 'image/jpeg', 'image/gif', 'jpg', 'png', 'jpeg', 'gif');
По идее, MIME типы можно убрать

2017-10-16 21:26 UTC, gohabereg requested changes
Не жалей пустых строк между кодом

2017-10-16 21:26 UTC, gohabereg commented on Image.class.php
> +        $this->fileExp = $this->fileExp[count($this->fileExp)-1];
Очень ненадежная проверочка будет

2017-10-16 21:26 UTC, gohabereg commented on Image.class.php
> +class Image {
Назови классы лучше `Uploader`, `FileUploader`, `LinkUploader`

2017-10-16 21:26 UTC, gohabereg commented on Uploader.php
> +if(is_uploaded_file($_FILES['ImageFile']['tmp_name'])) {
Перенеси эту проверку внутрь класса

2017-10-17 09:03 UTC, gohabereg requested changes

2017-10-17 09:03 UTC, gohabereg commented on lib/uploader/Image.class.php
> +        if (is_uploaded_file($img['tmp_name'])) {
Перепиши в формате:
```
if (!is_uploaded_file($img['tmp_name'])) {
    throw new Exception(...);
}

Тут код, когда условие true

2017-10-17 09:03 UTC, gohabereg commented on lib/uploader/Image.class.php
> +        file_put_contents($this->fileName, file_get_contents($_GET['ImageLink']));
Расставь пустые строки между логическими частями

2017-10-17 09:03 UTC, gohabereg commented on lib/uploader/Image.class.php
> +        $storage = new AWS_Storage();
Расставь пустые строки между логическими частями

2017-10-17 10:08 UTC, gohabereg requested changes

2017-10-17 10:08 UTC, gohabereg commented on lib/uploader/Image.class.php
> +        } else {
Else тут не нужен, поскольку если будет выкинут эксепшн, код дальше не будет выполнен

2017-10-17 12:30 UTC, gohabereg approved these changes

2017-10-17 14:01 UTC, talyguryn requested changes

2017-10-17 14:01 UTC, talyguryn commented on lib/uploader/Image.class.php
> +class Uploader {    #Абстрактный класс, в котором описываются допустимые расширения и максимальный размер, а так же методы проверки.
Комменты не так надо писать

2017-10-17 17:30 UTC, talyguryn approved these changes

2017-10-17 17:30 UTC, merged