Rate limiting
codex-team/capella pull request #138
Opened 2020-02-13 15:21 UTC by talyguryn

2020-02-13 18:17 UTC, neSpecc requested changes

2020-02-13 18:17 UTC, neSpecc commented on capella/src/controller/Form.php
> +            $key = 'uploadsBy_' . $ip;
move key composing to separated method

2020-02-13 18:26 UTC, talyguryn commented on capella/src/controller/Form.php
> +            $key = 'uploadsBy_' . $ip;
yea, of course it will be done

2020-02-15 09:55 UTC, khaydarov commented on capella/src/RateLimiter.php
> +
```suggestion
```

2020-02-15 09:55 UTC, khaydarov commented on capella/src/api/Response.php
> +        die(json_encode($responseData));
это ты так возвращаешь HTTP-ответ?)

2020-02-19 16:57 UTC, gohabereg requested changes

2020-02-19 16:57 UTC, gohabereg commented on capella/src/cache/Cache.php
> +        if (is_null($this->memcacheObj)) {
Doesn't `isAlive` method do the same?

2020-02-19 16:57 UTC, gohabereg commented on capella/src/controller/Form.php
> +                    'message' => 'Sorry, you cannot upload more than 3 images per minute.'
I guess you can use constants from ENV here

2020-02-19 16:57 UTC, gohabereg commented on capella/src/http/Response.php
> +    public static function TooManyRequests($retryAfter = 60)
Here also constant can be used

2020-02-25 17:27 UTC, gohabereg approved these changes

2020-02-25 17:46 UTC, neSpecc approved these changes

2020-02-25 17:46 UTC, neSpecc commented on capella/src/controller/Form.php
> +            /** Middleware to reduce image download intensity */
```suggestion
            /** Middleware to reduce image upload intensity */
```

2020-02-26 07:11 UTC, merged