Restricted access by tokens, images database
codex-team/capella pull request #139
Opened 2020-05-29 14:47 UTC by talyguryn

- save images data to database
- generating access tokens
- check image by its hash before saving

@todo update readme and index page

2020-05-29 19:13 UTC, neSpecc requested changes

2020-05-29 19:13 UTC, neSpecc commented on capella/src/Uploader.php
> +            'project-id' => $_POST['project-id']
projectId

2020-05-29 19:13 UTC, neSpecc commented on capella/src/Uploader.php
> +            'author' => Methods::getRequestSourceIp(),
вынести в getAuthor

2020-05-29 19:13 UTC, neSpecc commented on capella/public/app/js/project-form.js
> +  const showToken = (token) => {
нет доков

2020-05-29 19:13 UTC, neSpecc commented on capella/public/app/js/project-form.js
> +  const sendForm = (data) => {
нет доков

2020-05-29 19:13 UTC, neSpecc commented on capella/public/app/js/project-form.js
> +  const showToken = (token) => {
используй обычную функцию, вместо стрелочной

2020-05-29 19:13 UTC, neSpecc commented on capella/public/app/js/project-form.js
> +      name: document.getElementById('name') ? document.getElementById('name').value : '',
двойной поиск по дереву

2020-05-29 19:13 UTC, neSpecc commented on capella/src/bootstrap.php
> +if (isset($_GET['token'])) {
расхардкодить название поля

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +            $_POST['project-id'] = $this->checkProjectToken();
хардкод

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +            'id' => basename($imageData['link'], '.' . Uploader::TARGET_EXT), // Get ID as name without extension
верни коммент на место

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +        $token = isset($_POST['token']) ? $_POST['token'] : '';
```suggestion
        $token = !empty($_POST['token']) ? (string) $_POST['token'] : '';
```

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +    private function checkProjectToken() {
из названия следует, что она возвращает boolean или выплевывает ошибку. Ничего этого нет в коде

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +     * Check request token from POST params
проверяет на что?

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +            if (!!$mongoResponse && $mongoResponse['_id']) {
```suggestion
            if (!empty($mongoResponse['_id'])) {
```

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Project.php
> +                'name' => $_POST['name'],
```suggestion
                'name' => (string) $_POST['name'],
```

2020-05-29 19:13 UTC, neSpecc commented on capella/src/Uploader.php
> +        }
вынеси в метод checkForDuplicate

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Project.php
> +                'description' => $_POST['description'],
```suggestion
                'description' => (string) $_POST['description'],
```

2020-05-29 19:13 UTC, neSpecc commented on capella/src/controller/Project.php
> +                'email' => $_POST['email'],
```suggestion
                'email' => (string) $_POST['email'],
```

2020-05-29 19:13 UTC, neSpecc commented on capella/src/router.php
> +    /** Show main page */
комменты сплющило

2020-05-29 20:13 UTC, neSpecc requested changes
нет типов

2020-05-29 20:13 UTC, neSpecc commented on capella/src/controller/Form.php
> +            'id' => basename($imageData['link'], '.' . Uploader::TARGET_EXT), // Get ID as name without extension
теперь их два

2020-05-29 20:28 UTC, neSpecc approved these changes

2020-05-30 13:06 UTC, khaydarov commented on capella/composer.json
>      },
```php
"autoload": {
    "psr-4": {
      "App\\": "src/",
    }
  },
```

2020-05-30 13:06 UTC, khaydarov commented on capella/composer.json
>      },
PSR-4 описан стандарт автолоадинга классов. Если в композере пропишешь psr-4, то все твои классы будут доступны в пространстве имен App. Таким образом ты замкнешь приложение вокруг этого неймспейса

2020-05-30 13:06 UTC, khaydarov commented on capella/composer.json
>      },
и не нужно будет писать свой автолоадинг

2020-06-01 14:59 UTC, merged