Database class added
codex-team/capella pull request #14
Opened 2017-10-15 21:26 UTC by komantnick

2017-10-15 21:33 UTC, gohabereg requested changes

2017-10-15 21:33 UTC, gohabereg commented on capella.sql
> +INSERT INTO `capella-storage` (`id`, `dt_add`, `extension`, `ip`) VALUES
Дамп данных тут не нужен

2017-10-15 21:33 UTC, gohabereg commented on database.php
> +    {
Скобки лучше на ту же строку, где `if`

2017-10-15 21:33 UTC, gohabereg commented on database.php
> +    if (is_null($type)) {
Что-то с отступами

2017-10-15 21:33 UTC, gohabereg commented on database.php
> +        catch(PDOException $e){
Как пользователь узнает, что произошла ошибка?

2017-10-15 21:51 UTC, khaydarov requested changes

2017-10-15 21:51 UTC, khaydarov commented on data.php
> +$database = new DataBaseWorker();
Назови пожалуйста DatabaseWorker

2017-10-15 21:51 UTC, khaydarov commented on database.php
> +    private $user = 'root'; //or any user name
С отступами совсем беда:(

2017-10-15 21:51 UTC, khaydarov commented on database.php
> +	public function __construct(){
Фигурные скобки переносят на новую строчку при обявлении функции

`php
Function somefunc ()
{
   // body
}
`
А а условный операторах 
`php
If (condition) { 
 // code 
}`

Удобнее будет читать и тебе,  и нам и всем кто будет читать твой код.

2017-10-15 21:51 UTC, talyguryn commented on capella.sql
> +INSERT INTO `capella-storage` (`id`, `dt_add`, `extension`, `ip`) VALUES
@gohabereg миграции же. почему не нужен-то?

2017-10-16 14:52 UTC, komantnick reviewed
исправлено

2017-10-16 14:53 UTC, komantnick reviewed
исправлено

2017-10-16 19:20 UTC, khaydarov approved these changes

2017-10-16 19:51 UTC, talyguryn requested changes

2017-10-16 19:51 UTC, talyguryn commented on data.php
> +$ip=$database->getUserIP();
`$ip = $database->getUserIP();`

2017-10-16 19:51 UTC, talyguryn commented on data.php
> +require_once('database.php');
добавь перенос строки

2017-10-16 19:51 UTC, talyguryn commented on data.php
> +/*using of class:
```
/**
 * Function description
 *
 * @example ...
 */
```

2017-10-16 19:51 UTC, talyguryn commented on data.php
> +$database->query('INSERT INTO `capella-storage` (id,extension,ip) VALUES (:id,:extension,:ip)');
`capella-storage` надо вынести в константу

2017-10-16 19:51 UTC, talyguryn commented on data.php
> +/*we get $id and $extension from name of uploaded photo. example of code:
поправь внешний вид комментария

2017-10-16 19:51 UTC, talyguryn commented on data.php
> +$database->bind(':id', $id);
так и надо оформлять запросы?

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +class DatabaseWorker
Не хватает комментария-описания класса и примеров использования

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    private $dbh;
непонятное название переменной

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    private $stmt;
непонятное название переменной

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    private $host = 'localhost'; //or any other host name
параметры лучше оформить в виде массива

```php
private $config = array(
    'host'     => 'localhost',
    'user'     => 'root',
    'password' => '',
    'dbname'   => 'capella'
);
```

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    private $host = 'localhost'; //or any other host name
комментарии `//or any other host name` не несут смысловой нагрузки

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +        // Set options
добавляй пустые строки, там где это необходимо, чтобы код не сливался в одну кучу

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +        catch (PDOException $e) {
поправь внешний вид

```php
try {
    ...
} catch (PDOException $e) {
    ...
}
```

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +                $type = PDO::PARAM_INT;
посмотри, как надо делать отступы
http://php.net/manual/ru/control-structures.switch.php

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    public function getUserIP()
посмотри, как надо оформлять описание функций

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    //executing a database
посмотри, как надо оформлять описание функций

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    //query statement in out class
посмотри, как надо оформлять описание функций

2017-10-16 19:51 UTC, talyguryn commented on database.php
> +    //binding results to every entry of database
посмотри, как надо оформлять описание функций

2017-10-16 19:53 UTC, gohabereg commented on data.php
> +$database->bind(':id', $id);
Да, это PDO

2017-10-16 19:54 UTC, talyguryn requested changes

2017-10-16 19:54 UTC, talyguryn commented on database.php
> +    private $host = 'localhost'; //or any other host name
а вообще параметры подключения базы данных лучше вынести в конфигурационный файл. 
посмотри пример тут https://github.com/codex-team/capella/tree/master/lib/AWS

2017-10-16 21:28 UTC, gohabereg requested changes

2017-10-16 21:28 UTC, gohabereg commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Удали файлы из .idea из реквеста. А саму .idea/ положи в игнор

2017-10-16 21:28 UTC, gohabereg commented on lib/db/config.php
> +<?php
Этот файл назови config.php.sample, а файл с именем config.php положи в игнор

2017-10-16 21:33 UTC, talyguryn requested changes
Уже лучше

2017-10-16 21:33 UTC, talyguryn commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Добавь .idea/ в гитигнор

2017-10-16 21:33 UTC, talyguryn commented on lib/db/config.php
> +<?php
Добавь файл config.php в гитигнор, а этот файл переименуй в config.sample.php

2017-10-16 21:33 UTC, talyguryn commented on lib/db/database.php
> +<?php
Добавь пустую строку после этой

2017-10-16 21:33 UTC, talyguryn commented on lib/db/database.php
> + *
Либо строка лишняя, либо допиши пример работы с этим классом

2017-10-16 21:33 UTC, talyguryn commented on lib/db/config.php
> +define("HOST", "localhost");  //host of database
Это безопасно?

2017-10-16 21:33 UTC, talyguryn commented on lib/db/config.php
> +define("HOST", "localhost");  //host of database
Может лучше создать тут переменную $config, а этот файл подключить в какой-нибудь функции, которая распотрошит этот конфиг и задаст переменные в классе?

2017-10-17 09:48 UTC, gohabereg approved these changes

2017-10-17 10:16 UTC, komantnick commented on lib/db/config.php
> +define("HOST", "localhost");  //host of database
Думаю, что не безопасно

2017-10-17 15:33 UTC, neSpecc requested changes

2017-10-17 15:33 UTC, neSpecc commented on lib/db/database.php
> +    private $stmt;
коммент к свойству

2017-10-17 15:33 UTC, neSpecc commented on lib/db/database.php
> +        // Set DSN for PDO connection
пустая строка перед комментариями

2017-10-17 15:33 UTC, neSpecc commented on lib/db/database.php
> +        $dsn = 'mysql:host=' . $config['dbhost'] . ';dbname=' . $config['dbname'];
полное название для переменной

2017-10-17 15:33 UTC, neSpecc commented on lib/db/database.php
> +        $this->dbh = new PDO($dsn, $config['dbuser'], $config['dbpassword'], $options);
dbh — дать понятное и полное название

2017-10-17 15:33 UTC, neSpecc commented on lib/db/database.php
> +        $this->stmt = $this->dbh->prepare($query);
полное название для stmt

2017-10-17 15:39 UTC, komantnick commented on lib/db/database.php
> +        $this->stmt = $this->dbh->prepare($query);
stmt-statement handler

2017-10-17 15:39 UTC, komantnick commented on lib/db/database.php
> +        $this->dbh = new PDO($dsn, $config['dbuser'], $config['dbpassword'], $options);
dbh-database handler

2017-10-17 18:23 UTC, talyguryn approved these changes

2017-10-17 18:25 UTC, neSpecc approved these changes

2017-10-17 18:25 UTC, merged