Capella delivery
codex-team/capella pull request #16
Opened 2017-10-17 11:26 UTC by kinoshni68

2017-10-17 14:38 UTC, talyguryn requested changes

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +	require_once 'lib/AWS/Storage.php';
отступ не нужен

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +	require_once 'lib/AWS/Storage.php';
добавить перед этой строкой пустую строку

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +
пустая строка не нужна

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +		$memcacheObj = new Memcache;
нужны пробелы вместо табов

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +		$memcacheObj->connect('127.0.0.1', 11211) or die('Memcache not connect');
параметры подключения надо бы брать из конфига

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +		return (new AWS_Storage())->getImage($imgID);
помести новый класс в переменную

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +	* @param {string} $imgURL
```
/**
 *
```

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +	* example [[0] => ('title' => $title, 'params' => ('w' => $w, 'h' => $h[, 'x' => $x, 'y' => $y]))]
`@example`

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +	/**
не хватает описания функции

2017-10-17 14:38 UTC, talyguryn commented on Delivery.php
> +		if(!empty($cacheImg)) $imgWithFilters = $cacheImg;
`{ ... }`

2017-10-17 16:14 UTC, gohabereg requested changes

2017-10-17 16:14 UTC, gohabereg commented on lib/Delivery.php
> +        $cacheImg = $memcacheObj->get(md5($imgID+implode($filters)));
Лучше sha256

2017-10-17 16:14 UTC, gohabereg commented on lib/Delivery.php
> +            $imgURL = (new AWS_Storage())->getImage($imgID);
Лучше разнести на две строки

2017-10-17 16:14 UTC, gohabereg commented on lib/Delivery.php
> +            if ($filter->title == 'crop') {
Лучше switch...case

2017-10-17 16:14 UTC, gohabereg commented on lib/Delivery.php
> +            if ($filter->title == 'crop') {
Обращение к массиву через []

2017-10-17 16:14 UTC, gohabereg commented on lib/Delivery.php
> +        $memcacheObj->connect(MEMCACHE_HOST, MEMCACHE_PORT) or die('Memcache not connect');
Для обращения к полям класса используй `$this->memcacheObj...`

2017-10-17 17:46 UTC, talyguryn reviewed
А где config.sample.php?

2017-10-18 12:24 UTC, neSpecc requested changes

2017-10-18 12:24 UTC, neSpecc commented on .gitignore
> +.idea/
притяни мастера, там это уже есть

2017-10-18 12:24 UTC, neSpecc commented on lib/Delivery.php
> +    public function __construct($imgID1, $filters1) {
почему 1 ?

2017-10-19 14:50 UTC, closed without merging