Design & modified build settings
codex-team/capella pull request #40
Opened 2017-10-26 22:33 UTC by PolinaShneider

Added postcss-loader

2017-10-26 22:34 UTC, PolinaShneider commented
![screencapture-capella-local-1509057152159](https://user-images.githubusercontent.com/15448200/32080171-defa8e4c-bab6-11e7-9554-a95039242ede.png)

2017-10-26 23:13 UTC, talyguryn requested changes

2017-10-26 23:13 UTC, talyguryn commented on public/app/img/instagram-logo.svg
> +<?xml version="1.0" encoding="UTF-8"?>
надо прогнать через оптимайзер https://jakearchibald.github.io/svgomg/

2017-10-26 23:13 UTC, talyguryn commented on public/app/css/pages/index.css
> +.capella-background {
это не бэм 😒

2017-10-26 23:13 UTC, talyguryn commented on public/app/css/pages/index.css
> +.capella-btn {
btn? не жадничай. добавь буквы

2017-10-26 23:13 UTC, talyguryn commented on public/app/css/pages/index.css
> +.capella-btn:hover {
у тебя подключен постцсс

```
.upload-button {
    ...

    &:hover {
        ...
    }

    &:before {
        ...
    }
}
```

2017-10-30 21:32 UTC, PolinaShneider commented
![screencapture-capella-local-1509399090991](https://user-images.githubusercontent.com/15448200/32196810-f3b967bc-bdd2-11e7-903f-9280da74d6e7.png)

2017-11-05 16:08 UTC, gohabereg requested changes

2017-11-05 16:08 UTC, gohabereg commented on public/app/css/pages/index.css
> +    top: 0;
Перенеси эти свойства в начало

2017-11-05 16:08 UTC, gohabereg commented on public/app/css/pages/index.css
> +    margin: 0 auto;
И тут тоже неплохо бы отсортировать свойства

2017-11-05 16:08 UTC, gohabereg commented on public/app/css/pages/index.css
> +        margin-top: 35px;
И тут

2017-11-05 16:08 UTC, gohabereg commented on public/app/css/pages/index.css
> +        -webkit-appearance: none;
Это точно будет работать во всех браузерах?

2017-11-11 19:23 UTC, neSpecc requested changes

2017-11-11 19:23 UTC, neSpecc commented on public/app/css/pages/index.css
> +        width: 100%;
лишнее

2017-11-11 19:23 UTC, neSpecc commented on public/app/css/pages/index.css
> +        padding: 80px 0;
давай __content не через паддинг, а как-то по другому центрируем, чтобы на больших экранах он тоже был в центре по вертикали

2017-11-11 19:23 UTC, neSpecc commented on public/app/css/pages/index.css
> +        background: #6c0bd1;
вынеси цвет в переменную

2017-11-11 19:23 UTC, neSpecc commented on src/view/index.php
> +        <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
пути странные. И что за иконка?

2017-11-11 19:23 UTC, neSpecc commented on src/view/index.php
> +        <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
и type странный, это что?

2017-11-11 20:57 UTC, talyguryn approved these changes

2017-11-11 21:40 UTC, neSpecc approved these changes

2017-11-11 21:50 UTC, merged