Drag'n'drop basic form without design
codex-team/capella pull request #46
Opened 2017-10-28 21:43 UTC by komantnick

2017-10-28 21:54 UTC, talyguryn requested changes

2017-10-28 21:54 UTC, talyguryn commented on src/css/form.css
> +.zoneupload {
https://ru.bem.info/methodology/quick-start/

2017-10-28 21:54 UTC, talyguryn commented on src/js/form_script.js
> +
Мы не используем jquery

2017-11-19 20:05 UTC, gohabereg approved these changes

2017-11-19 20:22 UTC, neSpecc requested changes

2017-11-19 20:22 UTC, neSpecc commented on public/app/js/dragndrop.js
> +   * @param wrapper - page wrapper selector
нужно указывать тип параметров

2017-11-19 20:22 UTC, neSpecc commented on public/app/js/dragndrop.js
> + * Class for working with drag and drop files to browser
нужно задокументировать свойства класса

2017-11-19 20:40 UTC, talyguryn approved these changes

2017-11-19 20:44 UTC, neSpecc approved these changes

2017-11-19 20:45 UTC, merged