Add favicon
codex-team/capella pull request #62
Opened 2017-11-16 17:45 UTC by PolinaShneider

2017-11-16 22:34 UTC, talyguryn requested changes

2017-11-16 22:34 UTC, talyguryn commented on src/view/index.php
> +        <meta name="image" property="og:image" content="https://alpha.capella.ifmo.su/meta_img.png" />
тут должен быть полный адрес?

2017-11-16 22:34 UTC, talyguryn commented on src/view/index.php
> +        <meta name="image" property="og:image" content="https://alpha.capella.ifmo.su/meta_img.png" />
картинка meta_img.png? та квадратная?

2017-11-16 22:34 UTC, talyguryn commented on src/view/index.php
> +        <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
они точно все нужны?

2017-11-17 06:40 UTC, talyguryn requested changes

2017-11-17 06:40 UTC, talyguryn commented on src/view/index.php
> +        <meta name="image" property="og:image" content="https://alpha.capella.ifmo.su/meta_img.png" />
`content="<?= \Methods::getDomainAndProtocol(); ?>/meta_img.png"`

2017-11-18 19:10 UTC, talyguryn approved these changes

2017-11-18 19:10 UTC, gohabereg approved these changes

2017-11-18 19:12 UTC, neSpecc approved these changes

2017-11-18 19:13 UTC, merged