Ctrl v
codex-team/capella pull request #64
Opened 2017-11-16 23:31 UTC by Nikitos9I

created ctrl-v

2017-11-16 23:32 UTC, talyguryn requested changes

2017-11-16 23:32 UTC, talyguryn commented on public/app/js/buffer.js
> +  let text = document.createTextNode('UPLOADING');
?

2017-11-16 23:32 UTC, talyguryn commented on public/app/js/buffer.js
> +  let image = document.createElement('img');
?

2017-11-16 23:33 UTC, talyguryn requested changes

2017-11-16 23:33 UTC, talyguryn commented on public/app/js/buffer.js
> +  document.body.appendChild(image);
?

2017-11-16 23:34 UTC, talyguryn requested changes

2017-11-16 23:34 UTC, talyguryn commented on public/app/js/buffer.js
> +        document.body.removeChild(text);
?

2017-11-17 08:28 UTC, gohabereg requested changes

2017-11-17 08:28 UTC, gohabereg commented on public/app/js/buffer.js
> +    document.body.appendChild(text);
Откуда text?

2017-11-17 08:28 UTC, gohabereg commented on public/app/js/buffer.js
> +        blob = items[i].getAsFile();
Items может много?
Почему берем последний?

2017-11-17 08:28 UTC, gohabereg commented on public/app/js/buffer.js
> +    document.body.appendChild(text);
И зачем он нужен?

2017-11-17 08:28 UTC, gohabereg commented on public/app/js/buffer.js
> +let Clipboard = function () {
Перепиши на класс

2017-11-17 08:50 UTC, neSpecc requested changes

2017-11-17 08:50 UTC, neSpecc commented on public/app/js/main.js
> +capella.buffer = require('./buffer');
почему не `clipboard`?

2017-11-17 08:50 UTC, neSpecc commented on public/app/js/buffer.js
> +      if (items[i].type.indexOf('image') === 0) {
что ты хотел проверить этой строкой?

2017-11-17 08:50 UTC, neSpecc commented on public/app/js/buffer.js
> +        formData.append('files', blob, blob.name);
не понятна логика работы с FileReader. Нужно описать зачем и что делается. В обработчике onload никак не используется event и другие параметры, а используются внешние переменные — тогда не понятно зачем он нужен

2017-11-17 16:46 UTC, Nikitos9I commented on public/app/js/buffer.js
> +      if (items[i].type.indexOf('image') === 0) {
У меня items.type содержит в себе тип массивов данных, полученных с буфера. Там не только изображение, там text/html, text/... и много разной другой ерунды. Вместе со всем этим там лежит еще и image/{format} , который мне и нужен в данном случае. Более того, я знаю, что если type содержит в себе image, то вхождение этого слова начинается с 0 индекса. Поэтому я и проверяю, нашел ли я это слово в type или не нашел, если нашел -> продолжаю работать с ним

2017-11-17 16:58 UTC, Nikitos9I commented on public/app/js/buffer.js
> +      if (items[i].type.indexOf('image') === 0) {
Пробовал решать этот вопрос другим способом: через clipboard.getData(Image), но не получилось найти, но, к сожалению, это не работает

2017-11-17 16:58 UTC, Nikitos9I commented on public/app/js/buffer.js
> +        blob = items[i].getAsFile();
items - это весь буфер.
Мы берем не последний, а конкретно изображение

2017-11-17 17:05 UTC, Nikitos9I commented on public/app/js/buffer.js
> +      if (items[i].type.indexOf('image') === 0) {
я напишу к ней пояснение

2017-11-17 20:03 UTC, gohabereg approved these changes

2017-11-17 22:13 UTC, talyguryn approved these changes

2017-11-17 22:14 UTC, merged