Capella loading
codex-team/capella pull request #65
Opened 2017-11-17 21:34 UTC by PolinaShneider

2017-11-17 21:36 UTC, PolinaShneider commented
![screencapture-codex-dev-8888-1510953098376](https://user-images.githubusercontent.com/15448200/32970050-6cfd90f2-cbf8-11e7-839d-177572eb6f1d.png)

2017-11-21 17:44 UTC, gohabereg requested changes

2017-11-21 17:44 UTC, gohabereg commented on public/app/css/pages/index.css
> +                position: relative;
position в самый верх

2017-11-21 17:44 UTC, gohabereg commented on public/app/css/pages/index.css
> +                -moz-border-radius: 3px;
Это уже можно убрать

2017-11-21 17:44 UTC, gohabereg commented on public/app/js/scene.js
> +  let progressBar = document.getElementsByClassName('js-capella__uploading-progress')[0].querySelector('div');
Выглядит страшненько

2017-11-21 17:44 UTC, gohabereg commented on public/app/js/scene.js
> +      mainContainer.classList.add('capella--loading');
Класс можно в константу

2017-11-21 17:44 UTC, gohabereg commented on public/app/js/uploader.js
>      console.log(percentage + '%');
Лог можно убрать

2017-11-21 18:13 UTC, neSpecc requested changes

2017-11-21 18:13 UTC, neSpecc commented on public/app/js/scene.js
> +'use strict';
название модуля ни о чем не говорит. Комментариев нет

2017-11-21 18:13 UTC, neSpecc commented on public/app/js/uploader.js
> +    this._this = this;
wat

2017-11-21 18:13 UTC, neSpecc commented on public/app/svg/startup.svg
> +	<g id="spaceship-wrapper" transform="rotate(-50) translate(0, -50)" fill="#ffffff">
файл не оптимизирован

2017-11-23 17:49 UTC, talyguryn approved these changes

2017-11-23 17:51 UTC, gohabereg approved these changes

2017-11-23 17:52 UTC, neSpecc requested changes

2017-11-23 17:52 UTC, neSpecc commented on public/app/js/main.js
> +  if (window.navigator.userAgent.search('Safari') >= 0 && window.navigator.userAgent.search('Chrome') < 0) {
надо поменять на indexOf

2017-11-23 17:52 UTC, neSpecc commented on public/app/js/main.js
> +  if (window.navigator.userAgent.search('Safari') >= 0 && window.navigator.userAgent.search('Chrome') < 0) {
или includes

2017-11-23 17:52 UTC, neSpecc commented on public/app/js/main.js
> +  if (window.navigator.userAgent.search('Safari') >= 0 && window.navigator.userAgent.search('Chrome') < 0) {
и вынести это в метод

2017-11-23 18:23 UTC, neSpecc approved these changes

2017-11-23 18:23 UTC, merged