Return json response
codex-team/capella pull request #82
Opened 2017-11-22 05:55 UTC by talyguryn

2017-11-22 07:11 UTC, gohabereg requested changes

2017-11-22 07:11 UTC, gohabereg commented on src/api/Response.php
> +        self::returnJSON($responseData);
По умолчанию будет возвращаться `[]`. Это норм?

2017-11-22 07:11 UTC, gohabereg commented on src/api/Response.php
> +class Response
Очень странный класс. Ты просто переписал методы `\HTTP\Response`. Но это должны быть методы api. Типа `returnImage`, `returnError` и тд

2017-11-23 09:30 UTC, neSpecc requested changes

2017-11-23 09:30 UTC, neSpecc commented on src/controller/Form.php
> +                \API\Response::returnError(array(
может просто 
```php 
\API\Response::error()
```
```php 
\API\Response::success()
```
```php
\API\Response::json()
```

2017-11-23 10:38 UTC, gohabereg requested changes

2017-11-23 10:38 UTC, gohabereg commented on src/api/Response.php
> +    public static function showData($imageData)
Почему метод называется showData, а передается туда imageData?

2017-11-23 10:46 UTC, neSpecc approved these changes

2017-11-23 10:46 UTC, gohabereg approved these changes

2017-11-23 10:52 UTC, merged