Added router
codex-team/capella pull request #9
Opened 2017-10-12 16:55 UTC by Gollut

2017-10-12 17:09 UTC, khaydarov commented on router.php
> +            ++$filterId;
А почему в конце цикла у тебя инкремент, когда ты уже в конце цикла?

2017-10-13 12:48 UTC, khaydarov requested changes

2017-10-13 12:48 UTC, khaydarov commented on Dispatcher.php
> +    // URI path
добавляй комменты к функциям вот так:
```php
/**
  * @param {String} Url - descrintion
  * 
  * Зачем он нужен
  */```

https://www.phpdoc.org/

Тебе самому будет приятно потом читать свой код

2017-10-13 12:48 UTC, khaydarov commented on Dispatcher.php
> +                        $params = explode('&', $this->rawFilters[$filterId + 1]);
Код выглядит лучше, когда меньше в нем скобок и уровней, типа, 
```php
if something {
      for.... {
              if something1 {
               }
                if something 2 {
                        doingSomething {
                               somethingElse 
                         }
                 }
          }
}`

это можно решить так: делишь логику этой большой функции на несколько маленьких, например, отдаешь какой-то функции, а результат обрабатываешь дальше

```php
   if something {

         // condition 1
         $condition = $this->subFunc1($data)
         if ($condition1 is true) {
                $this->doSmthForCond1()
         else {
                $this->doSmthForCond2()
         }
}`

так код выглядит лучше и расширять удобнее, но смотри сам, зависит конечно от логики

2017-10-14 16:20 UTC, gohabereg requested changes

2017-10-14 16:20 UTC, gohabereg commented on Dispatcher.php
> +    public function __construct($uri, $filterList)
Нужно описать в комменте структуру `$filterList`
А типы переменных заключить в {}

2017-10-14 16:20 UTC, gohabereg commented on Dispatcher.php
> +    private function getParamData($varBlock, $paramString, $delimiter = false)
Приватные методы лучше размещать в конце класса

2017-10-14 16:20 UTC, gohabereg commented on Dispatcher.php
> +        $type     = explode('|', $varBlock)[1];
Можно обернуть в `list($variable, $type) = explode('|', $varBlock)`

2017-10-14 16:20 UTC, gohabereg commented on Dispatcher.php
> +        $paramsParts = preg_split("/[{}]+/", $pattern);
Зачем + в регекспе?

2017-10-15 17:43 UTC, neSpecc commented on Dispatcher.php
> +            $data = array('status' => 'Filter syntax error');
может лучше выплевывать ошибки?

2017-10-16 19:02 UTC, gohabereg requested changes

2017-10-16 19:02 UTC, gohabereg commented on Dispatcher.php
> +     * @param {array} $filterList Dictionary of supported filters and patterns in format [c' => ('title' => $title, 'pattern' => '{$varName|$varType}$delimiter{$varName|$varType}[$additionalParameter
Не понятно, что значит `c'` в начале

2017-10-16 19:02 UTC, gohabereg commented on router.php
> +$filtersData = $dispatcher->parseFilters();
Это можно прям в конструкторе вызывать, я думаю
А значение получать из публичного поля

2017-10-16 19:02 UTC, gohabereg commented on Dispatcher.php
> +        if (array_key_exists($this->rawFilters[$filterId], $this->filterList)) {
Такие условия лучше переписывать так:
```
if (!array_key_exists(...)) {
    throw new Exception(..)
};

тут код, когда условие true
```

Так гораздо проще читается, исчезают вложенные уровни

2017-10-16 19:02 UTC, gohabereg commented on Dispatcher.php
> +     * @return {array} in format [['status' => $f1Status,'filter1' => $f1Title, 'params' => f1Params],
Формат вроде поменялся уже

2017-10-16 20:02 UTC, talyguryn requested changes

2017-10-16 20:02 UTC, talyguryn commented on router.php
> +$imageData   = array('id' => $dispatcher->id, 'filters' => $dispatcher->parsedFilters);
```
$imageData = array(
    'id' => $dispatcher->id,
    'filters' => $dispatcher->parsedFilters
);
```

2017-10-16 20:02 UTC, talyguryn commented on Dispatcher.php
> +     * @param {array} $filterList Dictionary of supported filters and patterns in format ['filterName' => ('title' => $title, 'pattern' => '{$varName|$varType}$delimiter{$varName|$varType}[$additiona
невозможно прочитать

2017-10-16 20:02 UTC, talyguryn commented on Dispatcher.php
> + * Class UriDispatcher
пример использования нужен

2017-10-16 20:02 UTC, talyguryn commented on Dispatcher.php
> +        /** {array} in format [['filter1' => $f1Title, 'params' => f1Params],
напиши более ясный комментарий

2017-10-16 20:02 UTC, talyguryn commented on Dispatcher.php
> +        $paramData = $this->getParamData(
```
$paramData = $this->getParamData(
    $paramsParts[$paramsPartsCnt - 1],
    $paramString
);

2017-10-16 20:02 UTC, talyguryn commented on Dispatcher.php
> +        return $paramsPart              = array("paramString" => $paramString, "params" => $params);
```
return $paramsPart = array(
    "paramString" => $paramString,
    "params" => $params
);
```

2017-10-16 20:02 UTC, talyguryn commented on router.php
> +require 'Dispatcher.php';
пустую строку надо добавить

2017-10-16 20:02 UTC, talyguryn commented on router.php
> +const FILTERS = array(
```
const FILTERS = array(
    'c' => array(
        'title' => 'crop',
        'pattern' => '{w|int}x{h|int}[&{x|int},{y|int}]'
    ),
    'r' => array(
        'title' => 'resize',
        'pattern' => '{w}x{h}'
    )
);
```

2017-10-16 20:46 UTC, talyguryn approved these changes

2017-10-16 20:49 UTC, gohabereg approved these changes

2017-10-16 20:54 UTC, khaydarov approved these changes

2017-10-16 21:06 UTC, merged

2017-10-16 21:07 UTC, talyguryn commented
closes #2