Copy notification desktop
codex-team/capella pull request #92
Opened 2017-11-26 14:26 UTC by PolinaShneider

### Fix or Enhancement?

If it solves any issue then add the following line.

closes #number-of-issue

2017-11-28 00:27 UTC, gohabereg requested changes

2017-11-28 00:27 UTC, gohabereg commented on public/app/css/pages/result.css
> +    &__copied-desktop {
Скопированный десктоп?

2017-11-28 00:27 UTC, gohabereg commented on public/app/js/copyable.js
> +    this.copiedLink = document.querySelector('.js-result__copy-link');
`linkToCopy`?

2017-11-28 00:27 UTC, gohabereg commented on public/app/js/main.js
> +capella.toggleNotification = require('./toggleNotification');
Странно называть модуль с глагола

2017-11-28 00:27 UTC, gohabereg commented on public/app/js/toggleNotification.js
> +  let toggleButtonText = function () {
Тут не надо так же, как в функции сверху?

2017-11-28 08:55 UTC, neSpecc requested changes

2017-11-28 08:55 UTC, neSpecc commented on public/app/js/notificationToggler.js
> +  let textIsChangedTimer;
все переменный и константы нужно задокументировать

2017-11-28 08:55 UTC, neSpecc commented on public/app/js/notificationToggler.js
> +  const showTimeout = 3500;
давай 2s

2017-11-28 08:55 UTC, neSpecc commented on public/app/js/notificationToggler.js
> +    notificationElement.classList.remove('js-hidden');
нужно расхардкодить 'js-hidden'

2017-11-28 08:55 UTC, neSpecc commented on public/app/js/notificationToggler.js
> +    if (!event.ctrlKey && !event.metaKey && event.which != 2) {
с зажатым командом вообще ничего не нужно делать, нужно оставлять дефолтное поведение. Поэтому этот иф должен быть в начале функции, и условие должно быть обратное

2017-11-28 08:55 UTC, neSpecc commented on public/app/js/notificationToggler.js
> +  let toggleButtonText = function () {
на мобиле лучше использовать ту же механику, что и на десктопе

2017-11-28 08:55 UTC, neSpecc commented on src/view/result.php
> +                        <div class="result__is-copied js-result__is-copied js-hidden">
а можно этот элемент создавать скриптом в нужный момент?

2017-11-28 11:53 UTC, PolinaShneider commented on public/app/js/notificationToggler.js
> +  let toggleButtonText = function () {
В смысле ту же механику? На десктопе мы скрываем/показываем. На мобиле редактируем innerHTML элемента. Предлагаешь тоже скрывать/показывать?

2017-11-28 12:21 UTC, PolinaShneider commented on src/view/result.php
> +                        <div class="result__is-copied js-result__is-copied js-hidden">
Тут какой нюанс: если мы создаем этот элемент скриптом при нажатии на ссылку, то контент "прыгает". У меня этот элемент изначально с opacity 0, потом мы класс, отвечающий за это убираем. Элемент как бы есть изначально, и ничего не прыгает.

Можно создавать элемент с нулевой opacity на момент загрузки скрипта, а не на момент клика. Но зачем? Много строк кода получится, не проще ли обойтись HTML + CSS? :)

2017-12-01 06:29 UTC, talyguryn approved these changes

2017-12-01 08:57 UTC, gohabereg requested changes

2017-12-01 08:57 UTC, gohabereg commented on public/app/js/copyable.js
> +      this.clipboardButton.addEventListener('click', capella.notificationToggler.toggleCopiedIcon, false);
А если будет только один пункт? Упадет ошибка

2017-12-01 08:57 UTC, gohabereg commented on public/app/js/notificationToggler.js
> +    } else {
else не нужен?

2017-12-01 09:07 UTC, neSpecc requested changes

2017-12-01 09:07 UTC, neSpecc commented on src/view/result.php
> +                        <a name="js-copyable" class="result__copy-link js-result__copy-link" href="<?= $imageURL ?>" target="_blank"><?= $imageURL ?></a>
почему не повесить событие на весь див? зачем два события на разные элементы

2017-12-01 09:07 UTC, neSpecc commented on src/view/result.php
>                      <div name="js-copyable-authorize" class="result__copy">
а что значит authorize?

2017-12-01 10:10 UTC, PolinaShneider commented on src/view/result.php
>                      <div name="js-copyable-authorize" class="result__copy">
Это из copyable.js

2017-12-01 22:53 UTC, gohabereg approved these changes

2017-12-01 22:54 UTC, neSpecc approved these changes

2017-12-01 22:55 UTC, merged